export enum contentType {
  JSON = "application/json",
  HTML = "text/html",
  PLAIN_TEXT = "text/plain",
  XML = "application/xml",
  FORM_URLENCODED = "application/x-www-form-urlencoded",
  MULTIPART_FORM_DATA = "multipart/form-data",
  JAVASCRIPT = "application/javascript",
  CSS = "text/css",
  CSV = "text/csv",
  PNG = "image/png",
  JPEG = "image/jpeg",
  GIF = "image/gif",
  BMP = "image/bmp",
  WEBP = "image/webp",
  ICO = "image/x-icon",
  TIFF = "image/tiff",
  SVG = "image/svg+xml",
  PDF = "application/pdf",
  ZIP = "application/zip",
  GZIP = "application/gzip",
  OCTET_STREAM = "application/octet-stream",
}
